apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: njood-ns
  labels:
    app: wordpress
spec:
  storageClassName: ""
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi